#!/bin/bash

if [ $# == 0 ]; then
	echo "this operation needs at least one argument"
else
	for i ;do
		if [ -b "$i" ]; then echo "$i ist Blockdevice"; else
		if [ -h "$i" ]; then echo "$i ist keine regulaere Datei"; else
		if [ -f "$i" ]; then echo "$i existiert"; else
		if [ -d "$i" ]; then echo "$i ist ein Ordner";
		else echo "$i existiert nicht";
		fi
		fi
		fi
		fi

	done
fi

exit 0
