#!/bin/bash

if [ $# == 0 ]; then
	echo "this operation needs at least one argument"
else
	for i ;do
		if [ -b "$i" ]; then echo "$i ist Blockdevice";
		elif [ -h "$i" ]; then echo "$i ist keine regulaere Datei";
		elif [ -c "$i" ]; then echo "$i ist special character";
		elif [ -f "$i" ]; then echo "$i existiert";
		elif [ -d "$i" ]; then echo "$i ist ein Ordner";
		else echo "$i existiert nicht";
		fi
	done
fi

exit 0
